M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Wed 31 Aug 2022 10:25:46 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-31T22:25:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0389
%
G90
G05
T1
X2.1872Y-2.0909
X2.1872Y-2.3185
X2.1872Y-2.5969
X2.1872Y-2.8244
T2
X3.1919Y-2.0177
X3.1919Y-2.0886
T3
X2.9836Y-2.0299
X3.0636Y-2.0299
T4
X3.0236Y-2.2299
T0
M30
